In [3]:
import numpy as np

In [2]:
a = np.array([[10,120]])
b = np.array([[30,40]])
print(a)
print(b)
print()

(a+b).T

[[ 10 120]]
[[30 40]]



array([[ 40],
       [160]])

In [4]:
#subtracting 2 vectors
(a - b)
(a - b).T

array([[-20],
       [ 80]])

In [4]:
#scaler multiplication
a = 2
u = np.array([[30,32]])
(a * u).T

array([[60],
       [64]])

In [5]:
# dot product of 2 vectors
#for 2-D vectors, it is the equivalent to matrix multiplication

u = np.array([10,20])
v = np.array([38,39])

print(10 * 38 + 20 * 39)
np.dot(u,v)

1160


1160

In [7]:
#matrix addition
a = np.array([[12,10],[4,5],[30,40],])
b = np.array([[2,8],[46,63],[50,10],])

print(a, end="= a \n\n")
print(b, end= "= b \n\n")

a + b

[[12 10]
 [ 4  5]
 [30 40]]= a 

[[ 2  8]
 [46 63]
 [50 10]]= b 



array([[14, 18],
       [50, 68],
       [80, 50]])

In [8]:
#matix subtraction
a - b

array([[ 10,   2],
       [-42, -58],
       [-20,  30]])

In [9]:
#Matrix scalar multiplication
a = 4
b = np.array([[2,5],[3,7],[8,6],])

a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [10]:
a = [[5,10],[15,20]]
b = [10,12]

np.dot(a,b)

array([170, 390])

In [11]:
#Transpose a matrix
a = np.array([[5,10],[15,20],[25,30]])
print(a, end = "= a \n\n")
print(a.T, end = "=aT")

[[ 5 10]
 [15 20]
 [25 30]]= a 

[[ 5 15 25]
 [10 20 30]]=aT

In [12]:
#crearing an identity matrix

i1 = np.eye(2)
i2 = np.eye(3)
print(i1,end = "I1 \n\n")
print(i2,end = "I2 \n\n")

[[1. 0.]
 [0. 1.]]I1 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]I2 



In [15]:
#Inverse a matrix
a = np.array([
    [2,10,3],
    [29,44,65],
    [32,54,75],
])
print(a,end = " = a \n\n")
print(np.linalg.inv(a), end = " =  |a| ")

[[ 2 10  3]
 [29 44 65]
 [32 54 75]] = a 

[[ 0.234375    0.65625    -0.578125  ]
 [ 0.10602679 -0.06026786  0.04799107]
 [-0.17633929 -0.23660714  0.22544643]] =  |a| 