Numpy -- Numerical Python

Advantages of Numpy Arrays :
1. Allows several mathematical operations
2. Faster Operations

In [1]:
# Importing the Numpy Library
import numpy as np

  List Vs Numpy
  

In [2]:
from time import process_time

Time taken by a List

In [5]:
python_list =  [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end = process_time()

total_time_List = end - start_time
print(total_time_List)

0.0014131740000000725


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 

end_time = process_time()

total_time_numpy = end_time - start_time
print(total_time_numpy)

0.0017245840000001955


In [8]:
if(total_time_List > total_time_numpy) :
  print('List consume more time')
  print('Numpy array is much Faster')
else :
  print('Numpy array consume more time')
  print('List is faster than Numpy')

Numpy array consume more time
List is faster than Numpy


Numpy Arrays

In [9]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Nd represent n dimensional array,
arrays are similar to matrices

In [11]:
# creating a 1 dimensional array
numpyOneDim = np.array([1,2,3,4])
print(numpyOneDim)

[1 2 3 4]


In [12]:
numpyOneDim.shape

(4,)

2D Numpy Array

In [13]:
numpy2Dim = np.array([(1,2,3,4,5),(2,4,6,8,10)])
print(numpy2Dim)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


In [14]:

numpy2Dim.shape

(2, 5)

Playing with float values

In [15]:
numpyFloatValues = np.array([(2.3,4.2,5.6,2.3,5.1,6.9),(3.3,7.6,1.2,2.8,9.2,0.2)], dtype = float)
print(numpyFloatValues)

[[2.3 4.2 5.6 2.3 5.1 6.9]
 [3.3 7.6 1.2 2.8 9.2 0.2]]


In [16]:
numpyFloatValues.shape

(2, 6)

Initial Placeholders in numpy arrays

In [17]:
# Create a numpy arrays of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# Create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


As you can see above here you got 5 rows and 4 column with all 5 values.

In [20]:
# Create an identity matrix
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Create a numpy array with randome values!
randomNumpyArray = np.random.random((3,4))
print(randomNumpyArray)

[[0.68535233 0.94223646 0.25835834 0.61335266]
 [0.04845909 0.91400859 0.09956672 0.30635246]
 [0.48552279 0.68597317 0.74218917 0.05569986]]


But the main thing is all the values will be between 0 and 1.

In [22]:
# So, here importing random integer in python 
integerInRange = np.random.randint(10, 100,(4, 4))
print(integerInRange)

[[13 30 57 77]
 [26 79 31 88]
 [75 21 19 97]
 [52 59 50 37]]


array of evenly spaced values --> Specifying the number of values required

In [23]:
spValues = np.linspace(10,30,4)
print(spValues)

[10.         16.66666667 23.33333333 30.        ]


In [25]:
# in second case
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,4)
print(e)

[10 14 18 22 26]


Convert a list to a numpy array

In [26]:
# Just a List
print('Just a List')
list2 = [10,20,20,20,50]
print(list2)

# Converted to a numpy array
print('\nConverted to a numpy array')
numpy_array = np.asarray(list2)
print(numpy_array)
type(numpy_array)

Just a List
[10, 20, 20, 20, 50]

Converted to a numpy array
[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array 

In [ ]:
randomA = np.random.randint(10,90,(5,5))
print(randomA)

[[27 82 84 49 74]
 [20 21 78 13 45]
 [35 14 73 73 87]
 [80 52 35 73 87]
 [29 65 66 70 62]]


In [ ]:
# array dimension using this function
print(randomA.shape)

(5, 5)


In [ ]:
# number of dimension 
print(randomA.ndim)

2


In [ ]:
# checking the number of elements in an array
print(randomA.size)

25


In [ ]:
# checking the data type of the values in the array
print(randomA.dtype)

int64


Mathematical Operations on a numpy array 

In [ ]:
list3 = [1,2,3,4,5,6,7,8,9]
list4 = [10,11,12,13,14,15,16,17,18]

print(list3 + list4)

# Concetanate oor joinns two list



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [ ]:
a = np.random.randint(0,10(3,3))
b = np.random.randint(10,20(3,3))


TypeError: ignored